<a href="https://colab.research.google.com/github/hj-1006/hj_pyton_study/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EC%99%80_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 02 넘파이

In [ ]:
import numpy as np
a = np.array(range(10)).reshape((2,5))
b = a.transpose()
print('a\n',a)
print('b\n',b)


a
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
#6-7 배열로 마스킹
mask = np.array([0, 1, 1, 0], dtype = bool)
print(mask)

data = np.random.randn(4,2)
print('\n data 출력 \n',data)

print('\n 마스킹된 데이터 출력\n', data[mask])
print('\n마스킹 역전된 데이터 출력\n' , data[~mask])

[False  True  True False]
\data 출력 
 [[-0.49835105  0.74178332]
 [-0.29849148  0.72989896]
 [-0.26655689  0.45721216]
 [ 0.51278709 -0.21845265]]

 마스킹된 데이터 출력
 [[-0.29849148  0.72989896]
 [-0.26655689  0.45721216]]

마스킹 역전된 데이터 출력
 [[-0.49835105  0.74178332]
 [ 0.51278709 -0.21845265]]


In [ ]:
#6-8 조건식으로 마스킹
posit = data[data>0]
print('양수 데이터 출력', '\n', posit)

over1 = data[1][data[1]>0]
print('두번째 행의 양수 데이터 출력','\n',over1)




양수 데이터 출력 
 [0.74178332 0.72989896 0.45721216 0.51278709]
두번째 행의 양수 데이터 출력 
 [0.72989896]


In [ ]:
#6-9 얕은 복사
a = np.arange(6)
b = a
print(a)
print(b is a)
b[0] = 10
print(a)

[0 1 2 3 4 5]
True
[10  1  2  3  4  5]


In [ ]:
 #6-10 깊은 복사
a = np.arange(6)
c = a.copy()

print(c is a)

c[0] = 20
print('A :', a)
print('C :', c)

False
A : [0 1 2 3 4 5]
C : [20  1  2  3  4  5]


In [ ]:
from google.colab import files

f = files.upload()

Saving chocolate_rating.csv to chocolate_rating.csv


In [ ]:
import numpy as np
data = np.loadtxt('chocolate_rating.csv',delimiter=',')
print('차원:', data.ndim)
print('모양:', data.shape)
print('원소 수:', data.size)
print(data)

ratings_mean = data[:,3].mean()
print(ratings_mean)

high_level = data[data[:,3]>=4]
high_id = high_level[:,0].astype(np.int64)
print('우수 초콜릿 수:', high_id.size)
print(high_id)

high_kakao = high_level[:,2]
unique_values, value_counts = np.unique(high_kakao,return_counts=True)
print('카카오 함류량:', unique_values)
print('함류량별 빈도수:', value_counts)

max_index = np.argmax(value_counts)
print(unique_values[max_index])
print('우수 초콜릿', high_id.size,'가지 중',value_counts[max_index],\
      '가지의 카카오 함유량이',unique_values[max_index]*100,'%입니다.')

차원: 2
모양: (1795, 4)
원소 수: 7180
[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]
3.185933147632312
우수 초콜릿 수: 100
[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]
카카오 함류량: [0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]
함류량별 빈도수: [ 1  3  4  2  1  3  2  2 45  1 11  1  4 17  1  1  1]
0.7


In [ ]:
#6-

# 03 판다스 활용


In [1]:
import pandas as pd
a = pd.Series([1,2,3,4])
print(a)

b = pd.Series([1,2,3],index=['a','b','c'])
print(b)

0    1
1    2
2    3
3    4
dtype: int64
a    1
b    2
c    3
dtype: int64


In [2]:
#6-13 리스트로 데이터 프레임 생성
list1 = list([['한빛','남자','20','180'],
              ['한결','남자','21','177'],
              ['한라','여자','20','160']])
col_names = ['이름','성별','나이','키']
pd.DataFrame(list1, columns=col_names)


이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [3]:
#6-14 닉셔너리로 데이터 프레임 생성
dict1 = {'이름':{0:'한빛',1:'한결',2:'한라'},
         '성별':{0:'남성',1:'남성',2:'여성'},
         '키':{0:'180',1:'177',2:'160'}}

pd.DataFrame(dict1)

이름  성별    키
0  한빛  남성  180
1  한결  남성  177
2  한라  여성  160

In [5]:
#6-15 배열로 데이터프레임 생성
import numpy as np
import pandas as pd

arr1 = np.array([['한빛','남성','20','180'],
                 ['한결','남성','21','177'],
                 ['한라','여성','20','160'],])

col_names = ['이름','성별','나이','키']

pd.DataFrame(arr1, columns = col_names)

이름  성별  나이    키
0  한빛  남성  20  180
1  한결  남성  21  177
2  한라  여성  20  160

In [36]:
#6-16 csv 파일로 데이터프레임 생성
list1 = list([['허준호','남성','30','183'],
              ['이가원','여성','24','162'],
              ['배규민','남성','23','179'],
              ['고고림','남성','21','182'],
              ['이새봄','여성','28','160'],
              ['이보림','여성','26','163'],
              ['이루리','여성','24','157'],
              ['오나현','여성','24','172'],])

col_names = ['이름','성별','나이','키']

df = pd.DataFrame(list1, columns = col_names)

In [15]:
#6-17 데이터 프레임을 csv 파일로 저장
df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')

df2 = pd.read_csv('./file.csv',sep=',')



In [16]:
#6-18 모든 열 이름 조회
df.columns

Index(['이름', '성별', '나이', '키'], dtype='object')

In [18]:
#6-19 데이터프레임 값 개수와 빈도수 확인
df.describe()

이름  성별  나이    키
count     8   8   8    8
unique    8   2   7    8
top     허준호  여성  24  183
freq      1   5   2    1

In [19]:
#6-20 데이터프레임의 처음 새 행 검색
df.head(3)

이름  성별  나이    키
0  허준호  남성  30  183
1  이가원  여성  24  162
2  배규민  남성  23  179

In [23]:
#6-21 데이터프레임의 마지막 다섯 행 검색
df.tail(9)

이름  성별  나이    키
0  허준호  남성  30  183
1  이가원  여성  24  162
2  배규민  남성  23  179
3  고고림  남성  21  182
4  이새봄  여성  28  160
5  이보림  여성  26  163
6  이루리  여성  24  157
7  오나현  여성  24  172

In [21]:
#6-22 인덱스 기준으로 정렬
df.sort_index(axis=0).head()

이름  성별  나이    키
0  허준호  남성  30  183
1  이가원  여성  24  162
2  배규민  남성  23  179
3  고고림  남성  21  182
4  이새봄  여성  28  160

In [28]:
#6-23 열 기준으로 정렬 (ascending False는 내림 True는 올림차순)
df.sort_values(by=['나이','키'],ascending=False).head()

이름  성별  나이    키
4  이새봄  여성  28  160
5  이보림  여성  26  163
7  오나현  여성  24  172
6  이루리  여성  24  157
2  배규민  남성  23  179

In [30]:
#6-24 열 이름으로 데이터 조회
df[['이름','키']].head()

이름    키
0  허준호  183
1  이가원  162
2  배규민  179
3  고고림  182
4  이새봄  160

In [31]:
#6-25 인덱스로 데이터 조회
#1행부터 3행까지, 0열부터2열까지
df.iloc[1:4,0:3]

이름  성별  나이
1  이가원  여성  24
2  배규민  남성  23
3  고고림  남성  21

In [39]:
#6-26 조건식을 만족하는 데이터조회(1)
list1 = list([['허준호','남성',30,183],
              ['이가원','여성',24,162],
              ['배규민','남성',23,179],
              ['고고림','남성',21,182],
              ['이새봄','여성',28,160],
              ['이보림','여성',26,163],
              ['이루리','여성',24,157],
              ['오나현','여성',24,172],])

col_names = ['이름','성별','나이','키']

df = pd.DataFrame(list1, columns = col_names)

df[df['키']>175].head()

이름  성별  나이    키
0  허준호  남성  30  183
2  배규민  남성  23  179
3  고고림  남성  21  182

In [41]:
#6-28 리스트 요소와 일치하는 데이터 조회
df[df['나이'].isin([21,23])]

이름  성별  나이    키
2  배규민  남성  23  179
3  고고림  남성  21  182