<a href="https://colab.research.google.com/github/hj-1006/hj_pyton_study/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EC%99%80_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
a = np.array(range(10)).reshape((2,5))
b = a.transpose()
print('a\n',a)
print('b\n',b)


a
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [13]:
#6-7 배열로 마스킹
mask = np.array([0, 1, 1, 0], dtype = bool)
print(mask)

data = np.random.randn(4,2)
print('\n data 출력 \n',data)

print('\n 마스킹된 데이터 출력\n', data[mask])
print('\n마스킹 역전된 데이터 출력\n' , data[~mask])

[False  True  True False]
\data 출력 
 [[-0.49835105  0.74178332]
 [-0.29849148  0.72989896]
 [-0.26655689  0.45721216]
 [ 0.51278709 -0.21845265]]

 마스킹된 데이터 출력
 [[-0.29849148  0.72989896]
 [-0.26655689  0.45721216]]

마스킹 역전된 데이터 출력
 [[-0.49835105  0.74178332]
 [ 0.51278709 -0.21845265]]


In [14]:
#6-8 조건식으로 마스킹
posit = data[data>0]
print('양수 데이터 출력', '\n', posit)

over1 = data[1][data[1]>0]
print('두번째 행의 양수 데이터 출력','\n',over1)


양수 데이터 출력 
 [0.74178332 0.72989896 0.45721216 0.51278709]
두번째 행의 양수 데이터 출력 
 [0.72989896]
